# Configuration file for unit test runner at http://travis-ci.org/#!/pantheon-systems/travis
branches:
  only:
    - master
language: php
php:
  - 5.3
before_script:
  - composer install --prefer-dist --dev
script: phpunit --bootstrap=vendor/drush/drush/tests/drush_testcase.inc tests/